### ISSUE TITLE
Cloudflare error

### ISSUE THREAD

**Issue by Bryankesler** [bra1nDump/show-me-chatgpt-plugin#27] opened 2023-05-28 00:41 UTC
Getting this error

Create a simple diagram of a butterfly lifecycle

ChatGPT

2 / 2

Used Show Me
REQUEST TO SHOW ME
{
  "mermaid": "graph TB\n  E[\"Egg\"] -- \"Hatches into\" --> L[\"Larva (Caterpillar)\"]\n  L -- \"Transforms into\" --> P[\"Pupa (Chrysalis)\"]\n  P -- \"Emerges as\" --> B[\"Butterfly\"]\n  B -- \"Lays\" --> E"
}

RESPONSE FROM SHOW ME

<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Worker threw exception | showme.redstarplugin.com | Cloudflare</title></title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1101</span>
          <small class="heading-ray-id">Ray ID: 7ce2725bf875e86f &bull; 2023-05-28 00:40:35 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Worker threw exception</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>You've requested a page on a website (showme.redstarplugin.com) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. An unknown error occurred while rendering the page.</p>
          </div>

          
          <div class="cf-column">
            <h2 data-translate="what_can_i_do">What can I do?</h2>
            <p><strong>If you are the owner of this website:</strong><br />you should <a href="https://www.cloudflare.com/login?utm_source=error_100x" target="_blank">login to Cloudflare</a> and check the error logs for showme.redstarplugin.com.</p>
          </div>
          
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">7ce2725bf875e86f</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">23.102.140.115</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>

</body>
</html>

**Comment by bra1nDump** [comment] 2023-05-28 05:06
Looks like the " were not escaped in the request. I will double check Monday if that's the issue

/remind me in two days

**Comment by antondevson** [comment] 2023-05-28 06:13
I'm getting the same error. Ray ID: 7ce43e8fad15e752 among others

**Comment by bra1nDump** [comment] 2023-05-28 15:10
@antondevson & @Bryankesler thanks for reporting - this helped us get the attention on the issue and fixing it!
This is related to #26 which was caused by a kroki outage and solved by moving to our own kroki mermaid instance.

## Mitigation
- Move back to kroki as its maintainers fixed the outage

## Long term 
- Create our own kroki cluster that would have health checks in place to detect that companion containers (for example kroki-mermaid) are down and restart it. Even better - upstream that to kroki.
- Setup alerts on Mixpanel to notify us of outages

**Closed by bra1nDump** 2023-05-28 15:10 UTC
Labels: reminder
